### ISSUE TITLE
Wrap guide not visible

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-syntax#2]
Hello

It appears the wrap guide you can enable in the editor is invisible using this syntax theme.

Its HTML looks like this:

```
<div is="wrap-guide" class="wrap-guide" style="left: 780px; display: block;"></div>
```

By default, it shows up as a small vertical line to indicate where soft wrapping should occur or just as an indicator of how long your lines of code should be.

Its offset depends on the preferred line length set in the Atom editor settings. I'm not sure if it's enabled by default or needs to be toggled, but can't find any option to enable/disable it other than setting the preferred line length.

Thanks in advance

**Comment by tjkohli** [comment]
Thanks for finding. It's been fixed, and will be out in the next release.
