### ISSUE TITLE
Question regarding styling of comments

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-syntax#5]
Hello

I understand that comments are currently colored in a rather dark fashion in order to not divert the user's attention from the code itself. I also very much like how they light up when they are focused, so you can still read them when you want to look at them.

In this line of thought, I was wondering what you think about making the comments, when they are focused, even brighter than they are now. I've been working with the theme for a while now, and noticed that, even lit up, the comments are rather hard to read. Since I have my screen brightness set rather low, I first tried upping it. This helped, but in situations in daylight where the sun is shining in, even at 100% brightness (at that point I'm looking at the sun, myself 😄), the comments are still rather hard to read.

Thanks in advance

**Comment by tjkohli** [comment]
Hi @Gert-dev, thanks for the comment. I'll consider this for a future release. Until then, feel free to disable Focus Mode in the Nebula settings, or manually adjust the brightness of the comments.
