### ISSUE TITLE
Flashing reds in atom-beta

### ISSUE THREAD

**Issue by mrmurphy** [tjkohli/nebula-syntax#7]
This is strange, but I just upgraded Nebula (maybe it was the theme, and not the syntax package?) yesterday, and upgraded to Atom Beta (version 1.2.1-beta0), and now the red text against the dark background is subtly and constantly flashing:

![flashing-red](https://user-images.githubusercontent.com/1227109/30436321-19fd32ce-9929-11e7-92cc-782eb6a8e34b.gif)

Strange, right?

This on OS X, High Serra beta

**Comment by mrmurphy** [comment]
Also, I forgot to mention, this only happens with vim-mode-plus (version 1.4.0) installed and in insert mode. If I exit to command mode the flashing stops.

**Comment by tjkohli** [comment]
I can tell you that it's happening as a result of toggling between antialiased text rendering and normal text rendering, but I am not sure as to why it's happening for you. This tends to happen when the GPU is being used to render an element on the page (i.e. 3d transforms, etc.). I will revisit in the next Nebula update, though. Keep me posted!

**Comment by axynos** [comment]
Also happening on Windows 10 Atom version 1.21.0-beta2.

Found a quick workaround for it though - add this to your atom custom stylesheet.
```css
atom-text-editor {
  transform: translateX(0.0001px);
}
```

**Comment by chris-revell** [comment]
This has started happening for me as well. MacOS Sierra, Atom 1.21.0. It's quite distracting.

**Comment by tjkohli** [comment]
@axynos I tried that, but it causes other problems, such as causing incorrect offset of the Autocomplete Plus modal.

**Comment by tjkohli** [comment]
I've (seemingly) fixed the bug using a workaround without any adverse (known) side-effects, and it should be released shortly alongside other minor improvements.

**Comment by tjkohli** [comment]
Just for the record, it has been fixed with Nebula UI theme 0.8.0. Cheers!
